### PR TITLE
Update thorium-shell.desktop

### PR DESCRIPTION
**Pull request by sahashirshendu**
The path doesn't exist (in Arch, installed from AUR package)

### CODE REVIEW

**Comment by gz83** [comment]
It's LGTM for me, but can you provide more error information or link to some issues?

@sahashirshendu

**Comment by sahashirshendu** [comment]
Not much of an error, but in my system (Arch with KDE) there is no icon in application menu for `thorium shell` due to the faulty path which does not exist. Doing the above correction in icon-path in the desktop file works. [Because the AUR pkgbuild installs thorium in `/opt/thorium-browser`, not sure about other systems]

**Comment by gz83** [comment]
Handed over to Alex for further review

**Comment by Alex313031** [comment]
@sahashirshendu This is not how it should be. The file is correct, but rather the AUR maintainer is taking it upon himself to install thorium in a non-default location, so issues like this are going to happen. You should contact him and have him restore the installation dir that is used on all other linux distros.

**Pull request closed without merging**
