### PR TITLE
docs: add --recursive to the project clone command

### PR DESCRIPTION
**Pull request by qoijjj**
docs: add --recursive to the project clone command

### CODE REVIEW

**Review by gz83 — CHANGES_REQUESTED** [review]
From your PR, I found that you only modified the compilation guidelines for the Linux platform. Do the compilation guidelines for other platforms also need to be modified?

**Comment by qoijjj** [comment]
> From your PR, I found that you only modified the compilation guidelines for the Linux platform. Do the compilation guidelines for other platforms also need to be modified?

Fixed. I had to add this to the mac instructions as those instructions didn't even include instructions for cloning. 


As an aside, the instructions in the windows section say that downloading the zip is an option, but this won't function properly without the submodules.

**Review by gz83 — CHANGES_REQUESTED** [review]
There are still some files that have not been modified. You need to search for `git clone https://github.com/Alex313031/thorium.git` in the thorium repo to find out which files you need to modify.

**Comment by qoijjj** [comment]
> There are still some files that have not been modified. You need to search for `git clone https://github.com/Alex313031/thorium.git` in the thorium repo to find out which files you need to modify.

fixed

**Review by gz83 — CHANGES_REQUESTED** [review]
The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.

**Comment by qoijjj** [comment]
> The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.

ok I can do that but thorium is capitalized in many places in the docs

**Comment by gz83** [comment]
> > The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.
> 
> ok I can do that but thorium is capitalized in many places in the docs

You only need to modify Thorium in the code you modified, and no other modifications are required.  For example, line 35 in the install_deps.sh file.

@qoijjj

**Comment by qoijjj** [comment]
> > > The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.
> > 
> > 
> > ok I can do that but thorium is capitalized in many places in the docs
> 
> You only need to modify Thorium in the code you modified, and no other modifications are required. For example, line 35 in the install_deps.sh file.
> 
> @qoijjj

I didn't capitalize it there, it was already capitalized there.

**Comment by gz83** [comment]
> > > > The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.
> > > 
> > > 
> > > ok I can do that but thorium is capitalized in many places in the docs
> > 
> > 
> > You only need to modify Thorium in the code you modified, and no other modifications are required. For example, line 35 in the install_deps.sh file.
> > @qoijjj
> 
> I didn't capitalize it there, it was already capitalized there.

I mean modify Thorium to thorium, like line 35 in install_deps.sh.

@qoijjj

**Comment by qoijjj** [comment]
> > > > > The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.
> > > > 
> > > > 
> > > > ok I can do that but thorium is capitalized in many places in the docs
> > > 
> > > 
> > > You only need to modify Thorium in the code you modified, and no other modifications are required. For example, line 35 in the install_deps.sh file.
> > > @qoijjj
> > 
> > 
> > I didn't capitalize it there, it was already capitalized there.
> 
> I mean modify Thorium to thorium, like line 35 in install_deps.sh.
> 
> @qoijjj

I understand. You want me to change Thorium to thorium. It already was Thorium though, so that is out of scope for this change. I can make a separate PR fixing all of the capitalizations if you prefer.

**Comment by gz83** [comment]
> > > > > > The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.
> > > > > 
> > > > > 
> > > > > ok I can do that but thorium is capitalized in many places in the docs
> > > > 
> > > > 
> > > > You only need to modify Thorium in the code you modified, and no other modifications are required. For example, line 35 in the install_deps.sh file.
> > > > @qoijjj
> > > 
> > > 
> > > I didn't capitalize it there, it was already capitalized there.
> > 
> > 
> > I mean modify Thorium to thorium, like line 35 in install_deps.sh.
> > @qoijjj
> 
> I understand. You want me to change Thorium to thorium. It already was Thorium though, so that is out of scope for this change. I can make a separate PR fixing all of the capitalizations if you prefer.

There is no need to open a new PR, you only need to complete it in this PR.

@qoijjj

**Comment by qoijjj** [comment]
> > > > > > > The last question, in the modified code, Thorium should be changed to thorium to be consistent with the name of the repo.
> > > > > > 
> > > > > > 
> > > > > > ok I can do that but thorium is capitalized in many places in the docs
> > > > > 
> > > > > 
> > > > > You only need to modify Thorium in the code you modified, and no other modifications are required. For example, line 35 in the install_deps.sh file.
> > > > > @qoijjj
> > > > 
> > > > 
> > > > I didn't capitalize it there, it was already capitalized there.
> > > 
> > > 
> > > I mean modify Thorium to thorium, like line 35 in install_deps.sh.
> > > @qoijjj
> > 
> > 
> > I understand. You want me to change Thorium to thorium. It already was Thorium though, so that is out of scope for this change. I can make a separate PR fixing all of the capitalizations if you prefer.
> 
> There is no need to open a new PR, you only need to complete it in this PR.
> 
> @qoijjj

I will not be doing so as it is out of scope.

**Review by gz83 — CHANGES_REQUESTED** [review]
I will not approve this PR for the time being and will keep this PR in its current status, with final approval by Alex to follow.

**Comment by Alex313031** [comment]
@gz83 @qoijjj Yeah, can you change it to lowercase thorium instead of Thorium, that was an error on my part.

Also, can you put the --recursive before the URL. Either way will work on the user's side, but the proper way to enter the command would be:

git clone --recursive URLTOCLONE

**Comment by qoijjj** [comment]
> @gz83 @qoijjj Yeah, can you change it to lowercase thorium instead of Thorium, that was an error on my part.
> 
> Also, can you put the --recursive before the URL. Either way will work on the user's side, but the proper way to enter the command would be:
> 
> git clone --recursive URLTOCLONE

Again, the capitalization is out of scope for this change and is not specific to these lines. I can make a separate PR fixing all of the capitalizations in the repo but will not be doing so in this PR.

**Review by Alex313031 — APPROVED** [review]

**Comment by Alex313031** [comment]
@qoijjj On second thought, I need to update the docs for other stuff too, so I will update the capitalization when I do that as well, so no need to make another PR.

Anyway, I merged it, thanks sir.

**Comment by qoijjj** [comment]
> @qoijjj On second thought, I need to update the docs for other stuff too, so I will update the capitalization when I do that as well, so no need to make another PR.
> 
> Anyway, I merged it, thanks sir.

No problem, here's a PR to fix the capitalizations in all urls for the repo https://github.com/Alex313031/thorium/pull/223

**Pull request merged**
