### PR TITLE
Introducing new feature and updating patches

### PR DESCRIPTION
**Pull request by gz83**
@Alex313031 Please review, thank you.

### CODE REVIEW

**Comment by Alex313031** [comment]
@gz83 If I merge this, I will only take responsibility for the `[browser_commands.cc](https://github.com/Alex313031/thorium/pull/201/files#diff-b55914aba78598e18794548c657b2a4dbba9f0011eb2c10b18f50206672591c8)` file since it is already in thorium.

This is alot of files and I don't wanna add the work to each release. However, if you are okay with rebasing it for every release, we can add it. I will rebase that one file, then let you know when Im done, then you could update the other ones.

We could change this patch to being your responsibility, since I like updating the libjxl patch anyway, and that was previously going to be your responsibility.

**Comment by gz83** [comment]
I can and take responsibility for rebasing files other than browser_commands.cc, including restoring files needed for libjxl support, as I have communicated to you before.

We can add this feature to each version, and if there is anything that the Thorium project needs my help, I will provide support as much as I can.

**Comment by Alex313031** [comment]
@gz83 I don't want to put too much work on you. You can do one or the other if u want

**Comment by gz83** [comment]
Oh ok, I now choose to maintain the two patch files of libjxl repo and other files that I am responsible for. We can put this pull request on hold.

@Alex313031

**Comment by gz83** [comment]
Reopen

**Pull request closed without merging**
