### PR TITLE
update readme to include the removal of "vaapi on wayland" patch

### PR DESCRIPTION
**Pull request by eifr**

### CODE REVIEW

**Review by gz83 — CHANGES_REQUESTED** [review]
Sorry, your modification is incorrect and I do not support your PR.

**Comment by eifr** [comment]
@gz83 i just reflected the [patches](https://github.com/Alex313031/thorium/blob/78d27cbeab263a7299d3bbb87770d931737d8a96/infra/PATCHES.md?plain=1#L32) to the readme :\

**Comment by gz83** [comment]
I think this line can be removed, but I'll leave the PR to Alex for final review

**Comment by eifr** [comment]
@Alex313031

**Comment by Alex313031** [comment]
@eifr @gz83 Yeah, this patch was removed.

**Pull request merged**
