### PR TITLE
Update thorium.svg

### PR DESCRIPTION
**Pull request by ianalexis**
New logo concept for thorium to facilitate its differentiation with chromium, keeping a similar aesthetic to the current one.
If liked and approved I will generate the rest of the images needed.

### CODE REVIEW

**Review by gz83 — CHANGES_REQUESTED** [review]
Thanks for the new icon, but please share your ideas with Alex and get his approval before making these changes.

Since I haven't seen his approval or more details, I'll give it a -1 for the time being.

**Comment by ianalexis** [comment]
@gz83 this was my way to share my idea whitout an "issue" or just commenting it. I think that showing an idea with something done and proposing help to implement it is better than ordering some change.
I remain at your disposal. 
Rgrds

**Comment by gz83** [comment]
Can you share a general idea here and how you made the new icon? I just need to know more details at the moment, and also these details will help Alex in his subsequent review.

**Comment by ianalexis** [comment]
The main goal is to give thorium its own design. Now the "logo" is just chromium with a black circle in the middle instead of a white one. From what I saw that's because of the Technetium logo.
I tried to not change that much because you always use blue shades in everything so i tried to star in that line (the circular core color remains the chromium one).
The only change was a darker pallete of the same tone and a grayer shade of black to bring it closer to the rest of the palette.
This way the difference in the taskbar is noticeable without a different color.
If you like different base colors for a radical change here are others examples 
1 Thorium now, 2 new concept
3 new with green base, 4 new with orange base.
image

Maybe you want a full rework like mercury, in that case define a color pallete and concept/idea would be useful.

**Comment by gz83** [comment]
> The main goal is to give thorium its own design. Now the "logo" is just chromium with a black circle in the middle instead of a white one. From what I saw that's because of the Technetium logo. I tried to not change that much because you always use blue shades in everything so i tried to star in that line (the circular core color remains the chromium one). The only change was a darker pallete of the same tone and a grayer shade of black to bring it closer to the rest of the palette. This way the difference in the taskbar is noticeable without a different color. If you like different base colors for a radical change here are others examples 1 Thorium now, 2 new concept 3 new with green base, 4 new with orange base. [image](javascript:void(0))
> 
> Maybe you want a full rework like mercury, in that case define a color pallete and concept/idea would be useful.

Very good idea, well done

@ianalexis

**Comment by Danny3** [comment]
Interesting idea, but I still find the Chromium one (the first one) as the nicest.
I don't know why, maybe because I don't like darker colors / shades so much.

**Comment by Alex313031** [comment]
@ianalexis @gz83 @Danny3 @Malus-risus I've been debating and trying out different logos since I started the project in 2021. Everything I try, or that other people send to me, never seems quite right, and at this point, although the icon could be better, I will probably leave it.

**Comment by Kamey2024** [comment]
image
I think using tide pods swirld and colors in the Thorium logo could look cool.

**Comment by Enderteck** [comment]
Made this on in inkscape with changes to the original colors and some gradients.

I'd love if it was reviewed too: 

thorium

**Comment by nPHYN1T3** [comment]
This is the my Thorium icon from my icon pack.

https://github.com/nPHYN1T3/m0dw3rks-Icons/blob/main/apps/512/thorium.png

**Comment by Danny3** [comment]
> Made this on in inkscape with changes to the original colors and some gradients.
> 
> I'd love if it was reviewed too:
> 
> thorium

I like it!

**Comment by Enderteck** [comment]
I'll look into it. Maybe the titanium element letters instead of just a T tho.

**Comment by Danny3** [comment]
> I'll look into it. Maybe the titanium element letters instead of just a T tho.

As you wish!
I see here that Titanium element has the letter Ti as a symbol.
I guess it's cool, but might confuse some people why is Ti instead of Th or Tho for Thorium, the browser's name.
But you'll see better what is the best idea, if any.

**Comment by pixelpicnic** [comment]
I personally enjoy the greyscale aesthetic.
thorium_grey_logos

**Comment by Enderteck** [comment]
> i saw this and made one for fun, i love the app and want to contribute when i can with what i can, so got inspired by crystal structures and tried to give it a look that still reminded people of chromium, love the browser and keep up the good work :) thorium

Very nice ! Maybe with other colors/gradients in the middle ? Or a different shape ? Looks great !

**Comment by pixelpicnic** [comment]
got bored, made more:
thorium_grey_logos

just uploading a png, but all are svg

**Pull request closed without merging**
