### PR TITLE
Update hardcoded icons in toolbar

### PR DESCRIPTION
**Pull request by Aman9das**
I changed the icons back to the chromium ones, but this method is probably rudimentary. It'd be better to ship a thorium theme by default which can be replaced by the user easily

### CODE REVIEW

**Review by gz83 — CHANGES_REQUESTED** [review]
Please talk to Alex before making such changes.

If it's really necessary to change it, my idea would be to make a switch for the existing icon and the default icon that can be freely toggled on and off, rather than just simply changing the icon to the default.

@Aman9das @Alex313031

**Comment by Aman9das** [comment]
I do not expect this to be merged, any way to enable both default and branded icons are better.

This is just present in case such a thing is not possible, it'd easy to revert back to default icons.

**Comment by Alex313031** [comment]
@Aman9das @gz83 @Delphox

Many users have requested this, and I FINALLY did the work for it! Next release will have the flag `chrome://flags/#disable-thorium-icons`

See commit > https://github.com/Alex313031/thorium/commit/ad4ea69e7908bb0e013750db5b1d9fe8ec14f41a

If you have an AVX2 capable CPU, then you can try it live in the AVX2 repo, where I made a release slightly newer than the rest of the platforms, and it has this patch in it. > https://github.com/Alex313031/Thorium-Linux-AVX2/releases/tag/M120.0.6099.276

**Comment by Aman9das** [comment]
Lovely

**Pull request closed without merging**
